<script>
<?php
echo $this->jsData;
?>
$(document).ready(function(){
        var s1;
        var ticks;
 

<?php
foreach ($this->result as $key=>$value)
    {
    echo 's1 = [2, -6, 7, -1, 0, 3, -1, 7, 4, -6, -2, 0, 3];';
    echo "ticks = ['11/2016', '12/2016', '01/2017', '02/2017', '03/2017', 
            '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', 
            '10/2017', '11/2017'];";
    echo '    $.jqplot("'.$key.'", [s1], {
            seriesDefaults:{
                renderer:$.jqplot.BarRenderer,
                rendererOptions: { fillToZero: true },
                    pointLabels: { show: true }
            },
            axes: {
                // yaxis: { autoscale: true },
                xaxis: {
                    renderer: $.jqplot.CategoryAxisRenderer,
                    ticks: ticks
                }
            }
        });';
    }
?>
    });
</script>

<div id="chart7" style="height: 100px;"> </div>

<?php
foreach ($this->result as $key=>$value)
    {
    echo '<div id="'.$key.'Titolo"  style="height: 50px;">'.$value['Qualifica'].'</div>';
    echo '<div id="'.$key.'"  style="height: 100px;"> </div>';
    }
?>
