<script>
$(function() {
    $( "#GGtabs" ).tabs();
    <?php
    if ($this->addLink != '' && $this->addLabel != '')
    {
    ?>
    macroAddTabsBtn (".tabsul", "btn_tab_creanuovo", "+ Nuovo dipendente", <?php echo $this->addLink; ?>, "l");
    <?php
    }    
    ?>
});
</script>
<?php
echo $this->jsGrid;
?>

<div id="GGtabs">
<ul class="tabsul">
        <li><a href="#GGtabs-1">
            <?php 
            $translate = Zend_Registry::get('translate');
            echo $this->title.' '.$translate->_('(elenco)');
            ?>
            </a>
        </li>
</ul>
    <div id="GGtabs-1">
    <?php echo $this->grid; ?>
    </div>
</div>
