<?php
//$this->layout()->setLayout('mainpageLayout');
?>
<script>
	$(function() {
		$( "#GGtabs" ).tabs();
		$( "#GGtabsB" ).tabs();
	});
</script>
<style type="text/css">
    .colonna-style {
        padding: 0px;
        margin: 0px;
		width: 100%;
    }
    .colonna-home {
        display: table-cell;
        display:block;
        float:left;
        overflow: none;
    }
    .colonna-home-mid { float:left; display: table-cell; }
    .colonna-home-right {

        display: table-cell;
        float:left;
    }
	div>table{width: 100%;}
</style>