<script>
    $(function () {
        $("#GGtabs").tabs();
<?php
if ($this->addLink != '' && $this->addLabel != '')
    {
    echo 'macroAddTabsBtn(".tabsul", "btn_tab_creanuovo", "+ ' . $this->addLabel.'", "'.$this->addLink.'", "l");';
    }
?>

});


$(document).ready(function(){
<?php
    $toolTips = '';
    $plots = '';
    $allSeries = '';
    foreach($this->series AS $key=>$line)
        {
        if($toolTips != '' || $plots != '' || $allSeries != '') 
            {
            $toolTips .= ',';
            $plots .= ',';            
            $allSeries .= ',';            
            }
        $toolTips .= "'".$line['title']."'";
        $arrKey = explode('_', $key);
        $allSeries .= "{\nlabel: '".$line['title']."'\n";
        if(array_key_exists(1, $arrKey) && ($arrKey[1]+0) > 1)
            {
            $allSeries .= ",show: false,\nshowMarker: false,\nmarkerOptions: {show: false}\n";
//            $allSeries .= ",show: false,\nshowLine: false,\nshowMarkers: false\n";
            }
        $allSeries .= "}\n";
        $plots .= $key;
        echo 'var '.$key.'='.$line['values'] .";\n";
        }
    echo "var toolTip1 = [".$toolTips."];\n";
    echo "var plot1 = $.jqplot('chart1', [".$plots."], {\n";
?>
    axes:{
        xaxis:{
            renderer:$.jqplot.DateAxisRenderer
        }
    },
    legend: {
        show: true,
        location: 'e',
        renderer: $.jqplot.EnhancedLegendRenderer,
        rendererOptions: {
            numberColumns: 1,
            seriesToggleReplot: true,
            toolTips: toolTip1
        }
    },
    cursor:{
        show: true, 
        zoom: true
    }, 
    seriesDefaults: { 
        showMarker:false,
        pointLabels: { show:true } 
      },
    series: [
<?php
echo $allSeries;
?>
    ]
  });
});

//function printIt()
//    {
//    window.open().location = document.getElementsByTagName("canvas")[0].toDataURL("image/png");    
//    }    
        
function printIt()
    {
    var printCanvas=document.createElement('canvas');
    var printCtx=printCanvas.getContext('2d');
    $("#chart1").css("position", "relative");
    var zIndex = 1;
    $('#chart1 > canvas').each( function(e)
        {
        printCtx.drawImage(this.getImageData(),0,0,1000,600);
//        var image = new Image();
//        image.src = this.toDataURL("image/png");
//        $(image).css('position', 'absolute');
//        if(zIndex > 2)
//            {
//            $(image).css('left', '29px');
//            }
//        $(image).css('z-index', zIndex++);
//        printCtx.drawImage(image,0,0);
        });
    var img=new Image();
    img.onload=function(){
//    // print this snapshot image
        }
    img.src=printCanvas.toDataURL("image/png");
    var url=img.src;
    window.open(url,'Image','width="100%",height="100%",resizable=1');
    }
    
    
    
    
//    var myWindow = window.open("", "popup","width=1000,height=600,scrollbars=yes,resizable=yes," +  
//        "toolbar=no,directories=no,location=no,menubar=no,status=no,left=0,top=0");
//    var doc = myWindow.document;
//    doc.open();
//    var button = "<input type='button' id='btnPrint' value='Print' style='float: right;' onclick='window.print();'/>";
//    $(printContents).append($(button));
//    doc.write('<img src=$(printCtx).html());
//    doc.write(button);
//    doc.close();
//    }



//printCtx.drawImage(canvasZIndex1,0,0);
//printCtx.drawImage(canvasZIndex2,0,0);
//printCtx.drawImage(canvasZIndex3,0,0);
//
//    $(printContents).find(".tCheckboxes").remove();
        
//        var image = new Image();
//        image.src = this.toDataURL("image/png");
//        $(image).css('position', 'absolute');
//        if(zIndex > 2)
//            {
//            $(image).css('left', '29px');
//            }
//        $(image).css('z-index', zIndex++);
//        $(this).replaceWith(image);
//    var printContents = new $("#chart1");
        

</script>
<?php echo $this->javascript; ?>
<script>
    $(function () {
        $("#GGtabs").tabs();
        macroAddTabsBtn(".ui-tabs-nav", "esci", "Esci", "<?php echo $_SESSION['ggEsci-1_list']; ?>", "r");
    });
</script>
<div id="buttons_wrapper" style="width: 98%; overflow: hidden; ">
    <div id="buttons_content">
        <div style="float: right; display: inline;">
            <div id="printIt"class="buttonLike">
<!--                <a href= "javascript: html2canvas($('#chart1'), {
                                    onrendered: function(canvas) {
                                        theCanvas = canvas;
                                        document.body.appendChild(canvas);
                                        // Convert and download as image 
                                        Canvas2Image.saveAsPNG(canvas); 
                                        $('#img-out').append(canvas);
                                        // Clean up 
                                        //document.body.removeChild(canvas);
                                            });
                                        });
                                        ">Print</a>-->
<!--                <a href= "javascript: $('#chart1').printThis({
                     importCSS: true, importStyle: true,
                     header: '<h1>Grafico</h1>'});">Print</a>-->
                <a href= "javascript: printIt();">Print</a>
            </div>
            <div id="backWorld"class="buttonLike">
                <a href= "javascript:history.back()">Back</a>
            </div>
        </div>
    </div>
</div>

<div id="chart1" style="height:95%; width:98%;"></div>
<div id="printChart" style="height:95%; width:98%; display: none; z-index: 100;"></div>
