<?php echo $this->doctype(); ?>
<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head id="Head1">
        <?php
        echo $this->headMeta();
        $defaultNamespace = new Zend_Session_Namespace('Default');
        $translate = Zend_Registry::get('translate');
        echo $this->headTitle($defaultNamespace->cantiere);
        ?>
        <style>
            #loading2 {
                position: relative;
                width:20%;
                height:100px;
                background-color: #FFF;
                font:20px Arial, Helvetica, sans-serif;
                color:#000;
                padding:20px;
                margin:0 auto;
                border: 4px solid #888;
                text-align: center
            }
            li {list-style: none;}
            ul {list-style-type:none;}
        </style>
        <?php
        echo '<script language="JavaScript">var baseUrl="' . $this->baseUrl() . '";</script>';
        $this->jQuery()->onLoadCaptureStart();
        ?>

        $(function ()
        {

        $('.ui-multiselect').css({'width': '100%'});

        $('div#content').find('input[type="text"][readonly="readonly"]').each(function() {
        $(this).replaceWith('<div class="ReadonlyDisabledGG">' + $(this).val() + "</div>" );
        });
        $('div#content').find('textarea[readonly="readonly"]').each(function() {
        $(this).replaceWith('<div class="ReadonlyDisabledGG">' + $(this).val() + "</div>" );
        });
        $('div#content').find('input[type="file"][readonly="readonly"]').each(function() {
        $(this).replaceWith('<div class="ReadonlyDisabledGG">' + $(this).val() + "</div>" );
        });



        });
        jQuery(document).ready(function()
        {
        $("#breadCrumb").jBreadCrumb();
        })
        <?php
        $this->jQuery()->onLoadCaptureEnd();
        echo $this->jQuery();
        $config = Zend_Registry::get('config');

        $currEnv = $config->environment->get('zone');
        switch ($currEnv)
            {
        case 'produzione':
            $this->headLink()->prependStylesheet($this->baseUrl() . '/css/body_produzione.css');
            break;
        case 'te':
            $this->headLink()->prependStylesheet($this->baseUrl() . '/css/body_te.css');
            break;
        case 'test':
            $this->headLink()->prependStylesheet($this->baseUrl() . '/css/body_test.css');
            break;
        default:
            $this->headLink()->prependStylesheet($this->baseUrl() . '/css/body_test.css');
            break;
            }

//        $this->headLink()->prependStylesheet($this->baseUrl() . '/css/menusemplice.css');
        $this->headLink()->prependStylesheet($this->baseUrl() . '/prmenu/css/prmenu.css');
        $this->headLink()->prependStylesheet($this->baseUrl() . '/jBreadCrumb/Styles/BreadCrumb.css');
//        $this->headLink()->prependStylesheet($this->baseUrl() . '/jquery-ui-m/jquery.multiselect.css');
//        $this->headLink()->prependStylesheet($this->baseUrl() . '/jquery-ui-m/jquery.multiselect.filter.css');

        echo $this->headStyle();
        $this->headScript()->appendFile($this->baseUrl() . '/js/readonlydisabledgg.js');
//        $this->headScript()->appendFile($this->baseUrl() . '/js/menusemplice.js');
        $this->headScript()->appendFile($this->baseUrl() . '/prmenu/jquery.prmenu.js');
        $this->headScript()->appendFile($this->baseUrl() . '/js/menuIFDialog.js');
        $this->headScript()->appendFile($this->baseUrl() . '/jBreadCrumb/js/jquery.easing.1.3.js');
        $this->headScript()->appendFile($this->baseUrl() . '/jBreadCrumb/js/jquery.jBreadCrumb.1.1.js');
//        $this->headScript()->appendFile($this->baseUrl() . '/jquery-ui-m/src/jquery.multiselect.min.js');
        //$this->headScript()->appendFile($this->baseUrl() . '/jquery-ui-m/src/jquery.multiselect.min.filter.js');
        $this->headScript()->appendFile($this->baseUrl() . '/jquery-ui-m2/assets/prettify.js');
        $this->headScript()->appendFile($this->baseUrl() . '/jquery-ui/development-bundle/ui/i18n/jquery.ui.datepicker-it.js');
        echo $this->headScript();
        
//        if ($this->dojo()->isEnabled())
//            {
//            $this->dojo()->setLocalPath('/js/dojo/dojo/dojo.js')
//                    ->addStylesheetModule('dijit.themes.tundra')
//                    ->setDjConfigOption('usePlainJson', true);
//            }
        echo $this->headLink();
        ?>
        <link rel="shortcut icon" href="<?php
        if ($config->gglayout->get('favico'))
            {
            echo $this->baseUrl() . '/images/' . $config->gglayout->get('favico');
            }
        else
            {
            echo $this->baseUrl() . '/images/favico-sf-02.png';
            }
        ?>" type="image/x-icon" >

        <script type="text/javascript">
            document.write('<div id="loadingcaricamento" style="position:fixed;top:10%;z-index:999999;width:80%;left:10%;display:block;height:250px;padding:0;marging:0;"><div id="loading2"><img src="/public/images/clessidra.gif" alt="Caricamento" /><br><br>Elaborazione in corso attendere...</div></div>');

            window.onload = function () {
                document.getElementById("loadingcaricamento").style.display = "none";
            }
            
            $(document).ready(function () {
                $("#helpNote").dialog({
                  autoOpen: false,
                  closeOnEscape: false,
                  open: function(event, ui) { 
//                      $(".ui-dialog-titlebar-close").hide(); 
                  },
                  width: "auto",
                  title: "Help Note",
                  show: {
                      effect: "blind",
                      duration: 100
                  },
                  hide: {
                      effect: "blind",
                      duration: 100
                    }
                });
                
                $('.nav').prmenu({
                   "fontsize": "14",
                   "height": "30",
                   "case": "capitalize",
                   "linkbgcolor": "#286090",
                   "linktextcolor": "#ffffff",
                   "linktextweight": "400",
                   "linktextfont": "sans-serif",
                   "hoverdark": true
                   });

              });

            function openHelp()
                {
                request = $.ajax({
                url: baseUrl+'/aiuto/note',
                cache: false,
                type: 'post',
<?php
                echo 'data: {controller:"'.
                     strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()) .
                    '",action:"' .
                    strtolower(Zend_Controller_Front::getInstance()->getRequest()->getActionName()).
                        '"},';
?>
                success:function(result){  
        //            var parsed_data = JSON.parse(result);
        //            $('#newWP').html(JSON.stringify(parsed_data));
                    $("#helpNote").html(result);
                    $("#helpNote").dialog("open");
                    $('#helpNote').css('visibility', 'visible');
                    },
                error: function (data) {
                        console.log('An error occurred.');
                        console.log(data);
                        alert("Error");
                    }
            
                  });
                }

//                    type: frm.attr('method'),
//                    url: frm.attr('action'),
//                    data: frm.serialize(),

            function saveHelp()
                {
                var frm = $('#formAiuto');
                $.ajax({
                    url: baseUrl+'/aiuto/save-note',
                    cache: false,
                    type: 'post',
                    data: frm.serialize(),
                    success: function (data) {
                        console.log('Submission was successful.');
                        console.log(data);
                        closeHelp();
                    },
                    error: function (data) {
                        console.log('An error occurred.');
                        console.log(data);
                        closeHelp();
                    }
                  });
                }

            function closeHelp()
                {
                $("#helpNote").html("");
                $("#helpNote").dialog("close");
                $('#helpNote').css('visibility', 'none');
                }

        </script>

    </head>
    <body>

        <?php
        $config = Zend_Registry::get('config');
        if ($config->manutenzione->get('active'))
            {
            echo '<div class="manutenzione' . $config->manutenzione->get('liv') . '" ><marquee>' .
            $config->manutenzione->get('txt') . '</marquee></div>';
            }
        $_SESSION['ggEsci-1_list'] = $_SERVER["REQUEST_URI"];
        $_SESSION['ggEsci-2_list'] = $_SERVER["REQUEST_URI"];
        ?>
        <?php
        $userInfo = Zend_Auth::getInstance()->getStorage()->read();
        $defaultNamespace = new Zend_Session_Namespace('Default');
        $this->cantiere = "";
        if ($userInfo == null)
            {
            $redirectHelper = Zend_Controller_Action_HelperBroker::getStaticHelper('redirector');
            $redirectHelper->gotoUrl('/login/logout');
            $CartaIntestataA = '';
            }
        else
            {
            $this->cantiere = $defaultNamespace->cantiere;
            $this->cant2 = $defaultNamespace->cant2;
            }
        $this->cant2 = $defaultNamespace->cant2;
        $defaultNamespace->cant2 = '';
        ?>
        <div id="contenitore" class="cl-contenitore">
            <div id="barra-header-new" class="barra-header-bkg-x">
                <div id="arealavoroheader" class="barra-header-bkg">
                    <div class="barra-header-logo"> </div>
                    <div style="float:right">
                        <div id="togglelogin" class="togglelogin">
                            <?php
                            echo '<span class="loginTitolo"> ' .
                            $defaultNamespace->user["nome"] . ' ' .
                            $defaultNamespace->user["cognome"] . '</span>';
                            echo '<span class="loginTitolo"> (' .
                            $defaultNamespace->user["titolo_userlevel"] . ')</span>' .
                            '<span class="divisoreorizzontale"> | </span>';
                            echo $this->titlelogin;
                            echo '<span>' .
                            '<a href="/public/login/logout" ' .
                            'title="Logout" class="loginEsci">' .
                            '<img src="' . $this->baseUrl() .
                            '/images/logout.png" height="12" border="0">' .
                            '&nbsp;Logout</a></span>';
                            echo '<span class="divisoreorizzontale"> | </span>' .
                            '<span onclick="openHelp();return(false);">' .
                            '<img src="' . $this->baseUrl() .
                            '/images/menu-64.png" height="12" border="0">' .
                            '</span>';
//                            '<a href="/public/login/logout" ' .
//                            'title="Menu" class="loginEsci">' .
                            ?>
                        </div>
                    </div>
                    <div id="barra-header-title" >
                        <div style="margin-left: 320px; width: 100%">
                            <?php
                            echo '<h2 class="TTitolo">' . $this->cantiere . '</h2>';
                            echo '<h3 class="STitolo">' . $this->cant2 . '</h3>';
                            ?>
                        </div>
                    </div>
                    <div class="barra-header-menu">
                        <!-- menu -->
<!--                                    <div id="filler" style="display: inline-block;">
                                        filler &nbsp;
                                    </div>                                    -->
                        <div id="barra-myslidemenu_filler" style= "display: inline-block; width: 100%; height: 30; background-color: #286090">
                        <div id="barra-myslidemenu" style="max-width: 50%;">
                            <!--<div id="navigation" class="menusemplice" style="">-->
                            <div id="navigation">
                                <?php echo $this->navigation()->menu()->render(); ?>
                            </div>
                        </div>                                                    
                        </div>                                                    
                        <!-- close menu -->
                    </div>
                    <div class="clear"></div>
                    <div id="barra-header"></div>
                    <!--<div id="barra-header" style="height:120px"></div>-->
                </div>
            </div>
            <div id="content">


<!--                <div style="position:fixed;right:0px;top:300px;background-color:#00F;color:#FFF;float:right;z-index:200;">
                    <?php
//                    $aryAiuto = array("personale", "sopralluoghi", "dds", "pos", "rde", "verbali");
//                    $aryAiuto = array();
//                    $aryAiutoVal = "";
//                    $aryAiutoImp = "";
//                    if ($defaultNamespace->user['desc_userlevel'] == 'Impresa')
//                        {
//                        $aryAiutoImp = "imp";
//                        }
//                    if (in_array(strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()), $aryAiuto))
//                        {
//                        $aryAiutoVal = "/public/aiuto/aiuto/cont/" .
//                                strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()) .
//                                "/act/" .
//                                strtolower(Zend_Controller_Front::getInstance()->getRequest()->getActionName());
//                        ?>
                        <div style="display:block;text-align: center;width: 5px;height:80px;padding:4px 8px;">
                            <a href="#" onClick="iviewaiutodialog('<?php //echo $aryAiutoVal; ?>'); return false;" 
                               title="Aiuto in linea" style="width:10px;color:#Fff;">A i u t o</a>
                        </div>
                        <?php
//                        }
                    ?>
                </div>
                <div class="clear"></div>

                <div style="position:fixed;right:0px;top:200px;background-color:#00F;color:#FFF;float:right;z-index:200;">
                    <?php
//                    $aryAiuto = array("personale", "sopralluoghi", "dds", "pos", "rde", "verbali");
//                    $aryAiuto = array();
//                    $aryAiutoVal = "";
//                    $aryAiutoImp = "";
//                    if ($defaultNamespace->user['desc_userlevel'] == 'Impresa')
//                        {
//                        $aryAiutoImp = "imp";
//                        }
//                    if (in_array(strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()), $aryAiuto))
//                        {
//                        $aryAiutoVal = "/public/aiuto/aiuto" .
//                                strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()) .
//                                $aryAiutoImp .
//                                "/sezione/" .
//                                strtolower(Zend_Controller_Front::getInstance()->getRequest()->getActionName());
//                        $aryAiutoVal = "/public/aiuto/note/cont/" .
//                                strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()) .
//                                "/act/" .
//                                strtolower(Zend_Controller_Front::getInstance()->getRequest()->getActionName());
                        ?>
                        <div style="display:block;text-align: center;width: 5px;height:70px;padding:4px 8px;">
                            <a href="#" onClick="iviewaiutodialog('<?php //echo $aryAiutoVal; ?>'); return false;" 
                               title="Aiuto in linea" style="width:10px;color:#Fff;">N o t e</a></div>
                            <?php
//                            }
                        ?>
                </div>-->




                <div id="arealavorobody" class="arealavorobody">
                    <div id="capTitle" style="height: 100%">
                        <!-- ========================================= -->
                        <?php
                        echo '<div class="clear"></div>';
                        echo '<div id="breadCrumb" class="breadCrumb module">';
                        echo '<ul>';
                        echo '<li><a href="/public/index/">Home</a></li>';
                        echo '<li><a href="/public/index/">' . $translate->_('Scrivania') . '</a></li>';
                        if (isset($_SESSION['gigibreadc']))
                            {
                            foreach ($_SESSION['gigibreadc'] as $key => $value)
                                {
                                if (count($_SESSION['gigibreadc']) >= $key)
                                    {
                                    echo '<li><a href="' .
                                    $_SESSION['gigibreadc'][$key]['vai'] .
                                    '/">' . $translate->_($_SESSION['gigibreadc'][$key]['titolo']) . '</a></li>';
                                    }
                                else
                                    {
                                    echo '<li>' . $translate->_($_SESSION['gigibreadc'][0]['titolo']) . '</li>';
                                    }
                                }
                            }
                        echo '</ul></div>';
                        $defaultNamespace->title1 = '';
                        ?>

                        <!-- ========================================= -->
                        <div class="clear"></div>
                        <div style="height:8px;"></div>
                        <div>
                            <?php
                            echo $defaultNamespace->titleTest;
                            ?>
                        </div>
                        <div id="helpNote">
                        </div>
                        <div class="myContent">
                            <?php echo $this->layout()->content; ?>
                        </div>                        
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </body>
</html>
