<?php echo $this->doctype(); ?>
<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head id="Head1">
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo '<script language="JavaScript">var baseUrl="' . $this->baseUrl() . '";</script>';
        $this->jQuery()->onLoadCaptureStart();
        ?>
        $(document).ready(function(){
        $("input[type=submit]").button();
        });
        <?php
        $this->jQuery()->onLoadCaptureEnd();
        echo $this->jQuery();
        $this->headLink()->prependStylesheet($this->baseUrl() . '/css/body-login.css');
        echo $this->headStyle();
        echo $this->headScript();
//        if ($this->dojo()->isEnabled())
//            {
//            $this->dojo()->setLocalPath('/js/dojo/dojo/dojo.js')
//                    ->addStylesheetModule('dijit.themes.tundra')
//                    ->setDjConfigOption('usePlainJson', true);
//            }
        echo $this->headLink();
        ?>

    </head>
    <body>
        <div id="content">
<?php echo $this->layout()->content; ?>
            <div class="clear"></div>
        </div>
    </body>
</html>