<!-- <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>-->
<style>
	#loading2 {
		position: relative;
		width:20%;
		height:100px;
		background-color: #FFF;
		font:20px Arial, Helvetica, sans-serif;
		color:#000;
		padding:20px;
		margin:0 auto;
		border: 4px solid #888;
		text-align: center
	}
	li {list-style: none;}
	ul {list-style-type:none;}
	/*
	<div style="background:url(/images/loading_box.gif)left center repeat-x;border:1px solid #000; height:16px;80px;"></div>
	*/
</style>
<script type="text/javascript">window.onload = function () {
		document.getElementById("loadingcaricamento").style.display = "none";
	}
</script>
<script>
	$(function () {
		$(".chiudibox").hide();
		$(".espandibox").show();

		$('.espandibox').click(function () {
			$(".txtespandi").hide();
			$(".chiudibox").slideToggle();
		});

	});
</script>
<!-- </head>
<body> -->
		<h2><?php echo $this->message ?></h2>

<a href="#" class="espandibox" title="Visualizza/Nascondi Errore" >Mostra messaggio di errore.</a>
<div class="chiudibox" style="border:1px solid #888;padding:16px;background-color:#E8E8E8;margin:8px 0 0 0;">
	<p>
		<?php if (isset($this->exception)): ?>

				<h3>Exception information:</h3>
				<p>
		      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
				</p>

				<h3>Stack trace:</h3>
				<pre><?php echo $this->exception->getTraceAsString() ?>
				</pre>

				<h3>Request Parameters:</h3>
				<pre><?php echo var_export($this->request->getParams(), true) ?>
				</pre>
			<?php endif ?>
	<a href="#" class="espandibox">Nascondi messaggio di errore</a></div>
<!--
	</body>
</html>
-->
