<?php
	if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == "edit") {
		$ggStampa = '/public/' . Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . "/print/id/" . Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
	}
?>
<script>
	$(function () {
		$("#GGtabs").tabs();

		//	macroAddTabsBtn (".ui-tabs-nav", "esci", "Esci", "<?php echo $_SESSION['ggEsci-1_list']; ?>", "r");
		macroAddTabsBtn(".ui-tabs-nav", "precedente3", "form", "#", "r");
	});
</script>
<?php
	echo $this->javascript;
?>
<div id="GGtabs">
	<ul class="tabsul">
		<li><a href="#GGtabs-1"><?php if ($this->title) {
	echo $this->title;
} else {
	echo "Dettaglio";
} ?></a></li>
	</ul>
	<div id="GGtabs-1">
		<div id="form">
<?php echo $this->form; ?>
		</div>
	</div>
</div>
<?php

/*

<div id="form">
<br /><h1><center><?php echo $this->title; ?></center></h1>
<br />
<?php
echo $this->form . '</div>';
 * 
 */
